### ISSUE TITLE
Chain JSON support

### ISSUE THREAD

**Issue by ReiiYuki** [amritb/socketio-client-tool#12]
It might be better if it supports chain JSON such as 
```json
{
     "id" : "AAAA",
          "data": {
               "some_bool": true
          }
     }
```

**Comment by Nishchit14** [comment]
try [Firecamp](https://firecamp.app), It's a GUI client for SocketIO and WebSocket.

[Chrome Extension](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl)


![image](https://user-images.githubusercontent.com/5078921/50392367-df453900-0773-11e9-858b-92cf333b6020.png)

**Comment by ReiiYuki** [comment]
Wow that's seem great!
