### ISSUE TITLE
Emit and listen for events with multiple parameters

### ISSUE THREAD

**Issue by ashachakrapani** [amritb/socketio-client-tool#13]
Does the tool support events emitted or listened with multiple parameters? I don't seem to be able to send 4 different parameters. It transmits as a single string.

**Comment by Nishchit14** [comment]
try Firecamp, It's a GUI client for SocketIO and WebSocket.

Install [Chrome Extension](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl)

It has the features like, 
1.   Multiple params while emitting, 
2.  Save and Manage Listeners and Emitters body
3.  Generate auto code snippet for all langs.
4.  Save multiple emitters bodies/payload
5.  Can send cookie and headers


![image](https://user-images.githubusercontent.com/5078921/50392426-5549a000-0774-11e9-8e70-c92e20f4f1eb.png)
