### ISSUE TITLE
how this repo can connect to my localhost socket.io?

### ISSUE THREAD

**Issue by fikri2992** [amritb/socketio-client-tool#24]
first, thanks for your great work

i just want to know how this work? 
how can this apps conenct with my own localhost socket.io
i do access this repo directly from internet from http://amritb.github.io/socketio-client-tool/

how can this know my ip since i enter the localhost url

**Comment by amritb** [comment]
localhost actually has an IP: 127.0.0.1
When you start your node/go/python/etc web app locally on a specific port, e.g. 8080 - your local computer becomes a web server, serving http on 8080.
