### ISSUE TITLE
UI stops responding while using nodemon

### ISSUE THREAD

**Issue by tusharojha** [amritb/socketio-client-tool#28]
Hi there
I liked the socketio-client-tool, it is pretty useful and reduces my efforts for testing connections.
But I faced some issues while using this tool with nodemon, it doesn't respond if the nodemon re-builds my project. 

I think this issue is because when socket connection closes/restarts with the server, UI stops responding.

It would be great if this issue gets resolved.

**Comment by sarfraaz-talat** [comment]
@tusharojha this has been fixed in the latest commit f6578473f910db5dea13f682dfc9f1e1ccb4736b

**Comment by tusharojha** [comment]
Great Work @sarfraaz-talat 👍
