### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by kaissaroj** [amritb/socketio-client-tool#29]
How to connect to socket server with namespace in it?
Example url : http://localhost:8080/namespace

**Comment by JannikSt** [comment]
Hi @kaissaroj 
I am able to connect to my namespaces when I use your example URL provided with my namespace. 
My node.js server hosts on 0.0.0.0:8080 and an example namespace is /eventupdate, thus connecting to 0.0.0.0:8080/eventupdate works like a charm.

**Comment by amritb** [comment]
Thanks @JannikSt !
