### ISSUE TITLE
Network protocol violation error while running locally on windows 10

### ISSUE THREAD

**Issue by khushwaqt** [amritb/socketio-client-tool#30]
I have cloned this project in to my windows 10 machine, Install all dependencies using npm install. No error every thing runs smoothly. nmp run also has no errors. But when i open the URL from browser. it show network protocol violation error. 

```
Oops.

The site at http://192.168.100.10:8081/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the website owners to inform them of this problem.
```

**Comment by amritb** [comment]
released v2 of this tool with a complete re-write. Please create new issues if you see any problem.
