### ISSUE TITLE
Can't run last docker image - npm ERR! code ENOENT

### ISSUE THREAD

**Issue by farzinf** [amritb/socketio-client-tool#43]
Hi 
before every thing thanks for nice and cool tool 
in past i use this tools and run without any problems

today i latest pull docker and try to run it but i can't 
### 
### **error message :**

socketio_dev_1      | up to date in 3.77s
socketio_dev_1      | found 0 vulnerabilities
socketio_dev_1      | 
socketio_dev_1      | npm ERR! code ENOENT
socketio_dev_1      | npm ERR! syscall open
socketio_dev_1      | npm ERR! path /app/package.json
socketio_dev_1      | npm ERR! errno -2
socketio_dev_1      | npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
socketio_dev_1      | npm ERR! enoent This is related to npm not being able to find a file.
socketio_dev_1      | npm ERR! enoent 
socketio_dev_1      | 
socketio_dev_1      | npm ERR! A complete log of this run can be found in:
socketio_dev_1      | npm ERR!     /root/.npm/_logs/2020-12-30T05_37_11_176Z-debug.log
app-v1-real_socketio_dev_1 exited with code 254

### **docker-compose config:**

  socketio_dev:
    image: amritb/socketio-client-tool
    ports:
      - 8080:8080

**Comment by keeqler** [comment]
Same here.

**Comment by amritb** [comment]
Thanks - I will have a look.

**Comment by ccckblaze** [comment]
+1 +1 +1

**Comment by amritb** [comment]
this should be fixed now.
