### ISSUE TITLE
[BUG] Duplicate Listen Values

### ISSUE THREAD

**Issue by BarAppTeam** [amritb/socketio-client-tool#46]
Greetings,
Lately I've been having a problem duplicating values in your software
Each time you refresh the page it duplicates the values that exist in the Listen category

In addition, I also use the **nodemon** plugin which also causes the values to be duplicated because it restarts the session every time I save my project code

I would love to get help with the problem ❤
Thanks in advance

This image is for demonstration purposes:
![image](https://user-images.githubusercontent.com/77774766/107196211-023a1200-69fb-11eb-8d81-05caf2ce714a.png)

**Comment by amritb** [comment]
thanks - i will look into it

**Comment by BarAppTeam** [comment]
Hey @amritb, is there anything new with the bug?

**Comment by amritb** [comment]
No updates - I am still working on a fix.

**Comment by amritb** [comment]
Made some fixes - let me know if this solves your issue.
